# Fitting the Refined Model to the Data

With the table model constructed and the parameter space now understood, it was possible to start fitting to data. To refine the fitting process the processed XRISM dataset of NGC4151 was used. Modifications had to be made to the previous fitting code to include a rest frame spectrum, and photoelectric absorption. The rest frame model `XILLVER` was selected as implemented through `SpectralFitting.jl`.

The model used was:
```
PhotoelectricAbsorption * (PowerLaw + ConvolutionLineProfile(XillverD5))
```

where `PhotoelectricAbsorption`, `PowerLaw`, and `XillverD5` were implemented through `SpectralFitting.jl`. `ConvolutionLineProfile` is the table model defined here using the Johannsen metric, and convolving over the reflection spectrum to apply the relativistic properties to the emission lines. The parameters of the model are shown below. Note that the photon index appears in both the spectrum and the power law, and the inclination appears in both the spectrum and the line profile. These two pairs of parameters were bound together for fitting.

| Component    | Parameter                        | Initial Value | Bounds        |
|--------------|----------------------------------|---------------|---------------|
| Line Profile | Spin ($a$)                       | 0.998         | (0, 0.998)    |
|              | Corona Height ($h$)              | 19            | (3, 19)       |
|              | Inclination ($\theta$)           | 15            | (5, 85)       |
|              | $\alpha_{13}$                    | 0             | (-6, 10)      |
|              | $\epsilon_{3}$                   | 0             | (-8, 10)      |
| `XILLVER`    | Normalisation ($K$)              | 0.01          | (0, $\infty$) |
|              | Photon Index ($\Gamma$)          | 3.5           | (1, 5)        |
|              | Iron Abundance ($A_{\rm Fe}$)    | 1             | (0, 2)        |
|              | Ionisation ($\log\xi$)           | 0.5           | (0, 4)        |
|              | Density                          | 30            | (1, 30)       |
|              | Inclination ($\theta4)           | 15            | (5, 85)       |
| Absorption   | Equiv H column density ($\eta$H) | 10            | (0, 30)       |
| Power Law    | Normalisation ($K$)              | 40,000        | (0, $\infty$) |
|              | Photon Index ($\Gamma$)          | 3.5           | (1, 5)        |

